-- Start-screen splash settings — every knob for the dashboard GIF in one place.
--
-- ── Runtime knobs (the table below) ──────────────────────────────────────────
-- Take effect on the next nvim launch.
--
-- ── Art knobs (baked into the frames) ────────────────────────────────────────
-- Size, colors and source gif live in the SETTINGS block at the top of
-- scripts/gif-to-splash.py. Edit them, then regenerate with:
--
--   python3 scripts/gif-to-splash.py
--
--   WIDTH    art width in terminal columns
--   HEIGHT   art height in terminal rows; nil keeps the gif's aspect ratio
--            (each row shows 2 gif pixels via half-block characters)
--   PALETTE  number of colors; fewer = chunkier/retro, more = smoother
--            gradients but more highlight churn per frame
--   ALPHA_T  0-255 transparency cutoff; raise it to eat away semi-transparent
--            edge pixels, lower it to keep them
--   GIF/OUT  source gif and the generated lua module

return {
  -- Which splash to play: any module in lua/config/splashes/ generated by the
  -- script above (or by milli.nvim's `milli export <gif> -t lua`)
  module = "config.splashes.octopus",

  -- Animate at all? false shows just the static first frame
  animate = true,

  -- Playback speed multiplier: 1.0 = the gif's native timing,
  -- 0.5 = half speed, 2.0 = double speed
  speed = 1.0,

  -- Restart from frame 1 when the gif ends; false plays once and freezes on
  -- the last frame
  loop = true,

  -- Blank lines added below the art. The dashboard is centered vertically,
  -- so raising this nudges the art upward from true center
  padding = 0,
}
