--------------------------------------------------------------------------------
-- Hyprland — input.lua (was conf/input/input.conf)
--------------------------------------------------------------------------------

hl.config({
	input = {
		kb_layout = "us",
		-- Razer Blade has a standard PC layout, so the MacBook-era
		-- altwin:swap_alt_win swap is gone. Caps↔Escape stays.
		kb_options = "caps:swapescape",

		sensitivity = 0, -- mouse sensitivity
		-- accel_profile = "", -- flat or adaptive; empty means libinput default
		left_handed = false,
		follow_mouse = 1,
		float_switch_override_focus = 0,

		touchpad = {
			natural_scroll = true,
			tap_button_map = "lrm",
			clickfinger_behavior = true,
			disable_while_typing = true,
			scroll_factor = 0.5,
		},
	},
})

-- 3-finger horizontal swipe to switch workspaces (nice on the laptop;
-- carried over from the autogenerated config)
hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace",
})
