--------------------------------------------------------------------------------
-- Hyprland — monitors.lua (was conf/screen/monitors.conf)
--
-- Razer Blade 15 2022: the auto rule below picks the panel's preferred mode
-- (QHD@240Hz) and scale automatically — this is what the autogenerated config
-- did and it was confirmed working, so it stays.
--------------------------------------------------------------------------------

hl.monitor({
	output = "",
	mode = "preferred",
	position = "auto",
	scale = "auto",
})

-- Pin the panel if needed (QHD@240 confirmed working via auto):
-- hl.monitor({ output = "eDP-2", mode = "2560x1440@240", position = "0x0", scale = 1 })
