--------------------------------------------------------------------------------
-- Hyprland — master include order (safe + deterministic)
--
-- Lua rewrite of the old hyprland.conf for Hyprland 0.55+ (Razer Blade 15).
-- The previous autogenerated config is kept at hyprland.autogen.lua,
-- the old hyprlang config tree at conf/ for reference.
--------------------------------------------------------------------------------

-- 1) Base (variables live in lua/vars.lua, required by the modules below)
require("lua.env")

-- 2) Outputs & workspaces (must be set before rules/execs)
require("lua.monitors")
require("lua.workspaces")

-- 3) Core behavior & input
require("lua.misc")
require("lua.input")

-- 4) Visuals (layout, decorations, theme, animations)
require("lua.layout")
require("lua.decorations")
require("lua.colors")
require("lua.animations")

-- 5) Keybinds
require("lua.keybinds")

-- 6) Window/Layer rules (must come BEFORE execs so placement rules apply)
require("lua.rules")

-- 7) Runtime event handlers
require("lua.events")

-- 8) Autostart — start LAST so all the above is active
require("lua.execs")
