# ~/.config/sesh/sesh.toml

# New sessions start in a plain shell (no startup_command)
[default_session]
preview_command = "eza --all --git --icons --color=always {}"

# Optional: pin some “named” sessions you always want in the list
[[session]]
name = "dotfiles"
path = "~/github/config/dotnix"

[[session]]
name = "web"
path = "~/github/uni/L2_code/S1/programmation_web"

[[session]]
name = "systeme"
path = "~/github/uni/L2_code/S1/systemes"

[[session]]
name = "objet"
path = "~/github/uni/L2_code/S1/modelisation_prog_objet_1"
