#!/usr/bin/env python3
"""Convert a GIF into a milli.nvim-format Lua splash module using half-blocks."""

import os
import urllib.request
from PIL import Image, ImageSequence

# ── SETTINGS ─────────────────────────────────────────────────────────────────
# Documented in lua/config/splash-settings.lua; rerun this script after edits.
GIF = "/tmp/brrt.gif"  # downloaded from GIF_URL below if missing
GIF_URL = "https://raw.githubusercontent.com/ferrebarrat/brrtfetch/main/gifs/defaults/brrt.gif"
OUT = "/home/ritvik/github/config/dotnix/nvim/lua/config/splashes/octopus.lua"
WIDTH = 40  # art width in terminal columns
HEIGHT = None  # art height in terminal rows; None keeps the gif's aspect
PALETTE_SIZE = 24  # number of colors in the final art
ALPHA_T = 128  # 0-255 transparency cutoff for gif pixels
# ─────────────────────────────────────────────────────────────────────────────

if not os.path.exists(GIF):
    if not GIF_URL:
        raise SystemExit(f"gif not found: {GIF}")
    print("downloading", GIF_URL)
    urllib.request.urlretrieve(GIF_URL, GIF)

im = Image.open(GIF)
raw = [f.convert("RGBA") for f in ImageSequence.Iterator(im)]
durations = []
for i in range(im.n_frames):
    im.seek(i)
    durations.append(im.info.get("duration", 100))

# global bbox across all frames (alpha) so we can crop empty margins
minx, miny, maxx, maxy = 10**9, 10**9, -1, -1
for f in raw:
    bbox = f.getchannel("A").point(lambda a: 255 if a >= ALPHA_T else 0).getbbox()
    if bbox:
        minx = min(minx, bbox[0])
        miny = min(miny, bbox[1])
        maxx = max(maxx, bbox[2])
        maxy = max(maxy, bbox[3])
print("crop bbox:", (minx, miny, maxx, maxy))

cw, ch = maxx - minx, maxy - miny
# one terminal row = 2 gif pixel rows (half-block rendering)
target_h = HEIGHT * 2 if HEIGHT else round(WIDTH * ch / cw)
if target_h % 2:
    target_h += 1
print("pixel grid:", WIDTH, "x", target_h)

frames_px = [
    f.crop((minx, miny, maxx, maxy)).resize((WIDTH, target_h), Image.BOX) for f in raw
]

# quantize all opaque pixels to a small shared palette (keeps hl groups low)
opaque = []
for f in frames_px:
    for p in f.getdata():
        if p[3] >= ALPHA_T:
            opaque.append(p[:3])
uniq = list(set(opaque))
print("unique colors before quantize:", len(uniq))
strip = Image.new("RGB", (len(uniq), 1))
strip.putdata(uniq)
q = strip.quantize(PALETTE_SIZE, method=Image.MEDIANCUT)
pal = q.getpalette()[: PALETTE_SIZE * 3]
pal = [tuple(pal[i : i + 3]) for i in range(0, len(pal), 3)]


def nearest(c):
    return min(
        pal, key=lambda p: (p[0] - c[0]) ** 2 + (p[1] - c[1]) ** 2 + (p[2] - c[2]) ** 2
    )


cmap = {c: nearest(c) for c in uniq}
frames_q = []
for f in frames_px:
    nf = Image.new("RGBA", f.size)
    nf.putdata(
        [(*cmap[p[:3]], 255) if p[3] >= ALPHA_T else (0, 0, 0, 0) for p in f.getdata()]
    )
    frames_q.append(nf)
frames_px = frames_q

UP, DOWN = "▀", "▄"  # ▀ ▄


def cell(top, bot):
    """Return (char, fg, bg) for a pixel pair; colors are '#rrggbb' or None."""
    ta, ba = top[3] >= ALPHA_T, bot[3] >= ALPHA_T
    hex_ = lambda p: "#%02x%02x%02x" % p[:3]
    if not ta and not ba:
        return " ", None, None
    if ta and not ba:
        return UP, hex_(top), None
    if ba and not ta:
        return DOWN, hex_(bot), None
    return UP, hex_(top), hex_(bot)


frames, colors = [], []
for f in frames_px:
    px = f.load()
    flines, fcolors = [], []
    for r in range(target_h // 2):
        chars, runs = [], []
        byte = 0
        run = None  # [sb, eb, fg, bg]
        for c in range(WIDTH):
            ch_, fg, bg = cell(px[c, 2 * r], px[c, 2 * r + 1])
            blen = len(ch_.encode())
            if fg is None:
                run = None
            else:
                key = (fg, bg or "NONE")
                if run is not None and (run[2], run[3]) == key:
                    run[1] = byte + blen
                else:
                    run = [byte, byte + blen, key[0], key[1]]
                    runs.append(run)
            chars.append(ch_)
            byte += blen
        line = "".join(chars)
        flines.append(line)
        fcolors.append(runs)
    frames.append(flines)
    colors.append(fcolors)

# palette dedup -> local vars to keep LuaJIT constant count low
palette = {}
for fc in colors:
    for row in fc:
        for run in row:
            for col in (run[2], run[3]):
                if col != "NONE" and col not in palette:
                    palette[col] = "c%d" % (len(palette) + 1)
print("palette size:", len(palette))


def lua_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


out = []
out.append("-- Octopus splash (brrtfetch gifs/defaults/brrt.gif), half-block render")
out.append("-- Generated by a one-off converter; milli.nvim splash data format.")
for col, var in palette.items():
    out.append('local %s = "%s"' % (var, col))
out.append('local N = "NONE"')
out.append("return {")
out.append("  cols = %d," % WIDTH)
out.append("  rows = %d," % (target_h // 2))
out.append("  delays = { %s }," % ", ".join(str(d) for d in durations))
out.append("  frames = {")
for flines in frames:
    out.append("    { %s }," % ", ".join(lua_str(l) for l in flines))
out.append("  },")
out.append("  colors = {")
for fc in colors:
    rows = []
    for row in fc:
        runs = ",".join(
            "{%d,%d,%s,%s}" % (r[0], r[1], palette[r[2]], palette.get(r[3], "N"))
            for r in row
        )
        rows.append("{%s}" % runs)
    out.append("    { %s }," % ", ".join(rows))
out.append("  },")
out.append("}")

with open(OUT, "w") as fh:
    fh.write("\n".join(out) + "\n")
print("wrote", OUT, os.path.getsize(OUT) // 1024, "KB")
